name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Runs the sample CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test MY CI
        run: echo Hello, world!
      - name: Run final CI/CD
        run: |
          python3 -m unittest discover tests
          echo Done!
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
